# Workflow that defines how pull requests are built and tested.
name: Pull Requests
on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  #  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
  # CMAKE_VERSION: 3.18.4
  # CCACHE_VERSION: 3.7.7

jobs:
  run-pr-build:
    runs-on: macos-latest
    steps:
      - name: Build and Test Library
        uses: ./.github/actions/build-library
        with:
          scope: minimal

#  TODO: Figure out another way to publish Unit Test Results. Maybe https://github.com/mikepenz/action-junit-report
#  process-test-results:
#    needs: run-pr-build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v2
#        with:
#          path: artifacts
#
#      - name: Publish Annotation Processor Results
#        uses: EnricoMi/publish-unit-test-result-action@master
#        with:
#          files: artifacts/unit-test-results/realm-java/realm/realm-annotations-processor/build/test-results/test/TEST-*.xml
#
#      - name: Publish Example Project Results
#        uses: EnricoMi/publish-unit-test-result-action@master
#        with:
#          files: artifacts/unit-test-results/realm-java/examples/unitTestExample/build/test-results/**/TEST-*.xml
#
#      - name: Publish Library Test Results
#        uses: EnricoMi/publish-unit-test-result-action@master
#        with:
#          files: artifacts/unit-test-results/realm-java/realm/realm-library/build/test-results/**/TEST-*.xml
