# Define how pull requests are built and tested.
name: Pull Requests
on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  # GitHub Actions does not support variables. Use environments vars as a work-around
  BUILD_FLAGS: -PbuildTargetABIs=x86 -PenableLTO=false -PbuildCore=true

  # TODO: From DockerFile, not sure if needed
  CCACHE_CPP2: yes
  # CMAKE_VERSION: 3.18.4
  # CCACHE_VERSION: 3.7.7

jobs:
  run-pr-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # TODO How to optimize this? Can we cache it?
      - name: Install dependencies
        run: |
          brew install ninja
          brew install ccache

      # CCache setup copied from https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml
      # TODO: How to verify this works at all?
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      # TODO: Figure out why we require 3.18.4. Ideally it should just be minimum versions everywhere?
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.18.4'

      - name: Cache Gradle
        uses: actions/cache@v2.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # TODO: Figure out how to do different build flags depending on the build type
      - name: Build library
        run: ./gradlew assemble $BUILD_FLAGS --stacktrace

      - name: Run Tests
        run: ./gradlew check $BUILD_FLAGS --stacktrace

      # EnricoMi/publish-unit-test-result-action@v1 only works on Linux, so as a work-around
      # we archive the test results from mac-os and download them to a Linux runner.
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: |
            realm/realm-annotations-processor/build/test-results/test/TEST-*.xml
            examples/unitTestExample/build/test-results/**/TEST-*.xml
            realm/realm-library/build/test-results/**/TEST-*.xml

  process-test-results:
    needs: run-pr-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Annotation Processor Results
        uses: EnricoMi/publish-unit-test-result-action@master
        with:
          files: artifacts/realm/realm-annotations-processor/build/test-results/test/TEST-*.xml

      - name: Publish Example Project Results
        uses: EnricoMi/publish-unit-test-result-action@master
        with:
          files: artifacts/examples/unitTestExample/build/test-results/**/TEST-*.xml

      - name: Publish Library Test Results
        uses: EnricoMi/publish-unit-test-result-action@master
        with:
          files: artifacts/realm/realm-library/build/test-results/**/TEST-*.xml

#jobs:
#  build:
#    strategy:
#      matrix:
#        os: [macOS-latest, windows-latest, ubuntu-latest]
#        job: [instrumentation, test]
#        exclude:
#          - os: windows-latest
#            job: instrumentation
#
#    runs-on: ${{matrix.os}}
#
#    steps:
#      - name: Checkout the repo
#        uses: actions/checkout@v2
#      - name: Validate Gradle Wrapper
#        uses: gradle/wrapper-validation-action@v1
#      - name: Cache intellij download
#        uses: actions/cache@v2.1.0
#        with:
#          path: lib/download
#          key: intellij-${{ hashFiles('gradle/dependencies.gradle') }}
#      - name: Cache gradle
#        uses: actions/cache@v2.1.0
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Run ubuntu tests
#        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
#        run: |
#          ./gradlew build -x :.sqldelight-idea-plugin:b4ight-gradle-plugin:test --stacktrace
#          ./gradlew :sqldelight-gradle-plugin:test --tests="com.squareup.sqldelight.tests.*"
#          ./gradlew :sqldelight-gradle-plugin:test --tests="com.squareup.sqldelight.integrations.*"
#
#      - name: Run the IntelliJ plugin
#        if: matrix.os == 'ubuntu-latest' && matrix.job == 'instrumentation'
#        run: ./gradlew :sqldelight-idea-plugin:build --stacktrace
#      - name: Verify IntelliJ plugin
#        if: matrix.os == 'ubuntu-latest' && matrix.job == 'instrumentation'
#        run: |
#          ./gradlew :sqldelight-idea-plugin:runPluginVerifier
#
#      - name: Run windows tests
#        if: matrix.os == 'windows-latest'
#        run: ./gradlew mingwTest sqldelight-idea-plugin:check --stacktrace
#
#      - name: Run instrumentation tests
#        if: matrix.os == 'macOS-latest' && matrix.job == 'instrumentation'
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedCheck :sqldelight-gradle-plugin:build --stacktrace -PInstrumentation
#      - name: Run ios tests
#        if: matrix.os == 'macOS-latest' && matrix.job == 'test'
#        run: ./gradlew iosX64Test --stacktrace
#
#      - name: Bundle the build report
#        if: failure()
#        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
#      - name: Upload the build report
#        if: failure()
#        uses: actions/upload-artifact@master
#        with:
#          name: error-report
#          path: build-reports.zip

#env:
#  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"